//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Void-Craft.EU")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2025-2026 Void-Craft.EU")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Official Minecraft Launcher for the Void-Craft.EU community.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2.1.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2.1.1+19291114625f4bf8309f568c83b0c4f30efa4869")]
[assembly: System.Reflection.AssemblyProductAttribute("Void-Craft Launcher")]
[assembly: System.Reflection.AssemblyTitleAttribute("VoidCraftLauncher")]
[assembly: System.Reflection.AssemblyVersionAttribute("2.1.1.0")]

// Vygenerované třídou WriteCodeFragment nástroje MSBuild

