//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Void-Craft.EU")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2025-2026 Void-Craft.EU")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Official Minecraft Launcher for the Void-Craft.EU community.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("3.1.8.1")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("3.1.8.1+da039cd1df41da9c6de7a67df9eb7147d3d10e23")]
[assembly: System.Reflection.AssemblyProductAttribute("Void-Craft Launcher")]
[assembly: System.Reflection.AssemblyTitleAttribute("VoidCraftLauncher")]
[assembly: System.Reflection.AssemblyVersionAttribute("3.1.8.1")]

// Vygenerované třídou WriteCodeFragment nástroje MSBuild

